name: push_widgets_example
publish_to: 'none'
description: Example app demonstrating the push_widgets package.
version: 0.1.0+1

environment:
  sdk: ^3.9.2
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  push_widgets:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true