name: push_widgets
description: "Prefixed widgets (PW*) and Material 3 theme for Flutter apps."
version: 0.1.1
homepage: https://github.com/yourname/push_widgets
repository: https://github.com/yourname/push_widgets
issue_tracker: https://github.com/yourname/push_widgets/issues
documentation: https://github.com/yourname/push_widgets#readme
topics:
  - widgets
  - ui
  - material3
  - theming
  - cupertino

environment:
  sdk: ^3.9.2
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  # Optional: cupertino icons if examples or widgets use them
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  # Assets/fonts can be added later as needed.
